@startuml
left to right direction
actor Guest as g

package Colors{
  usecase "Log out" as UC1
  usecase "Search colors" as UC2
  usecase "Add colors" as UC3
  usecase "Log in" as UC4
}

g --> UC1
g --> UC2
g --> UC3
g --> UC4
@enduml
